import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import About from './about';
import Contact from './contact';
import Divider from './divider';
import Footer from './footer';
import Heading from './heading';
import Login from './login';
import Navbar from './navbar';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar></Navbar>
			<Heading></Heading>
			<Divider msg=' About'></Divider>
			<About></About>
			<Divider msg='Contact'></Divider>
			<Contact></Contact>
			<Divider msg='Login'></Divider>
			<Login></Login>
			<Footer></Footer>
		</div>
	);
}
